FROM golang:1.17.2-alpine3.14 as build

WORKDIR /devapp

COPY /example-backend .

ENV REQUEST_ORIGIN=http://localhost:8000

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o server

FROM scratch

WORKDIR /prodapp

COPY --from=build /devapp/server /

EXPOSE 8080

ENTRYPOINT [ "/server" ]
