version: '3.5'

services:
  redis:
    image: redis
  frontend:
    image: image-frontend
    ports:
      - 5000:5000   
  backend:
    image: image-backend
    ports: 
      - 8080:8080
    environment:
      - REDIS_HOST=redis
    restart: unless-stopped
    

      