version: '3.5'

services:
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
  redis:
    image: redis
  frontend:
    image: image-frontend
  backend:
    image: image-backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    restart: unless-stopped
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80